2 api_name: tensorflow.sysconfig.get_lib
3 api_description: Returns the filesystem path to the TensorFlow library directory
  as a string.
4 api_signature: '"tf.sysconfig.get_lib()"'
5 api_details: ''
6 api_parameters: []
7 api_usage_example: null
8 api_shape: ''
