2 api_name: tensorflow.sysconfig.get_include
3 api_description: Returns the directory path containing TensorFlow C++ header files.
4 api_signature: tf.sysconfig.get_include()
5 api_details: ''
6 api_parameters: []
7 api_usage_example: null
8 api_shape: ''
